org: ${env:ORG_NAME}
service: api-producto-bebe

provider:
  name: aws
  region: us-east-1
  runtime: nodejs20.x
  memorySize: 1024
  timeout: 30
  iam:
    role: ${env:IAM_ROLE_ARN}
  environment:
    TABLE_PRODUCTOS: ${sls:stage}-${self:service}-t_productos
    VALIDAR_TOKEN_FUNCTION_NAME: api-usuario-bebe-${sls:stage}-validarToken
    BUCKET_PRODUCTOS_NAME: ${sls:stage}-${self:service}-productos
    BUCKET_PRODUCTOS_URL: https://${self:provider.environment.BUCKET_PRODUCTOS_NAME}.s3.${self:provider.region}.amazonaws.com

package:
  patterns:
    - 'node_modules/**'  
    - 'node_modules/swagger-ui-express/**'
    - 'node_modules/swagger-jsdoc/**'
    - 'node_modules/doctrine/**' 
    - 'node_modules/argparse/**'   
    - 'node_modules/js-yaml/**'    
    - 'swagger.js'
    - 'swagger.json'
functions:
  listarProducto:
    handler: ListarProducto.handler
    events:
      - http:
          path: /producto/listar
          method: post
          cors: true

  crearProducto:
    handler: CrearProducto.handler
    events:
      - http:
          path: /producto/crear
          method: post
          cors: true

  buscarProducto:
    handler: BuscarProducto.handler
    events:
      - http:
          path: /producto/buscar
          method: post
          cors: true

  modificarProducto:
    handler: ModificarProducto.handler
    events:
      - http:
          path: /producto/modificar
          method: put
          cors: true

  eliminarProducto:
    handler: EliminarProducto.handler
    events:
      - http:
          path: /producto/eliminar
          method: delete
          cors: true
  subirImagenProducto:
    handler: subirImagenProducto.handler
    events:
      - http:
          path: /producto/subirimagen
          method: post
          cors: true

          
  actualizarProductos:
    handler: mv-busqueda/lambda/lambda_actualizar_productos.lambda_handler
    events:
      - stream:
          type: dynamodb
          arn:
            Fn::GetAtt:
              - TablaProductos
              - StreamArn
    environment:
      API_INDEXADOR_URL: http://34.205.2.254:8000/indexar

  swaggerUI:
    handler: swagger.handler
    events:
      - http:
          path: /swagger
          method: get
          cors: true
      - http:
          path: /swagger/{proxy+}
          method: get
          cors: true


resources:
  Resources:
    TablaProductos:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.TABLE_PRODUCTOS}
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: tenant_id
            AttributeType: S
          - AttributeName: producto_id
            AttributeType: S
        KeySchema:
          - AttributeName: tenant_id
            KeyType: HASH
          - AttributeName: producto_id
            KeyType: RANGE
        StreamSpecification:
          StreamViewType: NEW_IMAGE
    BucketProductos:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:provider.environment.BUCKET_PRODUCTOS_NAME}
        OwnershipControls:
          Rules:
            - ObjectOwnership: ObjectWriter  # Requiere esto para usar ACLs
        PublicAccessBlockConfiguration:
          BlockPublicAcls: false
          IgnorePublicAcls: false
          BlockPublicPolicy: false
          RestrictPublicBuckets: false
        CorsConfiguration:
          CorsRules:
            - AllowedOrigins:
                - "*"
              AllowedMethods:
                - GET
              AllowedHeaders:
                - "*"
              MaxAge: 3000


      
      
