org: ${env:ORG_NAME}
service: api-producto-bebe

provider:
  name: aws
  region: us-east-1
  runtime: nodejs20.x
  memorySize: 1024
  timeout: 30
  iam:
    role: ${env:IAM_ROLE_ARN}
  environment:
    TABLE_PRODUCTOS: ${sls:stage}-${self:service}-t_productos
    VALIDAR_TOKEN_FUNCTION_NAME: api-usuario-bebe-${sls:stage}-validarToken

functions:
  listarProducto:
    handler: ListarProducto.handler
    events:
      - http:
          path: /producto/listar
          method: post
          cors: true

  crearProducto:
    handler: CrearProducto.handler
    events:
      - http:
          path: /producto/crear
          method: post
          cors: true

  buscarProducto:
    handler: BuscarProducto.handler
    events:
      - http:
          path: /producto/buscar
          method: post
          cors: true

  modificarProducto:
    handler: ModificarProducto.handler
    events:
      - http:
          path: /producto/modificar
          method: put
          cors: true

  eliminarProducto:
    handler: EliminarProducto.handler
    events:
      - http:
          path: /producto/eliminar
          method: delete
          cors: true

resources:
  Resources:
    TablaProductos:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.TABLE_PRODUCTOS}
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: tenant_id
            AttributeType: S
          - AttributeName: producto_id
            AttributeType: S
        KeySchema:
          - AttributeName: tenant_id
            KeyType: HASH
          - AttributeName: producto_id
            KeyType: RANGE
        StreamSpecification:
          StreamViewType: NEW_IMAGE
