org: ${env:ORG_NAME}
service: api-usuario-bebe

provider:
  name: aws
  region: us-east-1
  runtime: python3.13
  memorySize: 1024
  timeout: 30
  iam:
    role: ${env:IAM_ROLE_ARN}
  environment:
    TABLE_USERS: ${sls:stage}-${self:service}-usuarios
    TABLE_TOKENS: ${sls:stage}-${self:service}-tokens

functions:

  registrarUsuario:
    handler: RegistroUsuario.lambda_handler
    events:
      - http:
          path: /usuario/signup
          method: post
          cors: true

  loginUsuario:
    handler: LoginUsuario.lambda_handler
    events:
      - http:
          path: /usuario/login
          method: post
          cors: true

  validarToken:
    handler: ValidarTokenUsuario.lambda_handler
    # No se expone públicamente
    

resources:
  Resources:

    TablaUsuarios:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.TABLE_USERS}
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: tenant_id
            AttributeType: S
          - AttributeName: user_id
            AttributeType: S
          - AttributeName: email
            AttributeType: S
        KeySchema:
          - AttributeName: tenant_id
            KeyType: HASH
          - AttributeName: user_id
            KeyType: RANGE
        GlobalSecondaryIndexes:
          - IndexName: EmailTenantIndex  # Nombre del GSI
            KeySchema:
              - AttributeName: tenant_id  # El tenant_id como clave de partición
                KeyType: HASH
              - AttributeName: email     # El correo electrónico como clave de ordenamiento
                KeyType: RANGE
            Projection:
              ProjectionType: ALL  # Incluir todos los atributos del item
            ProvisionedThroughput:
              ReadCapacityUnits: 5
              WriteCapacityUnits: 5

    TablaTokensAcceso:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.TABLE_TOKENS}
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: token
            AttributeType: S
        KeySchema:
          - AttributeName: token
            KeyType: HASH
